services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ELASTIC_PASSWORD=q1w2e3r4
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 8096M

  opensearch:
    image: opensearchproject/opensearch:3.0.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - plugins.security.ssl.http.enabled=false
      - plugins.security.ssl.transport.enabled=false
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=ForBenchmark1234!
    volumes:
      - opensearch:/usr/share/opensearch/data
    ports:
      - "9201:9200"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 8096M

  pgvector-IVFFlat:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: pgvector-ivfflat
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=q1w2e3r4
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"
    volumes:
      - pg-IVFFlat:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 8096M

  pgvector-HNSW:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: pgvector-hnsw
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=q1w2e3r4
      - POSTGRES_DB=postgres
    ports:
      - "15433:5432"
    volumes:
      - pg-HNSW:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 8096M

  qdrant:
    image: qdrant/qdrant:v1.14.0
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant:/qdrant/storage
    ulimits:
      nofile: 65535
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 8096M

volumes:
  elasticsearch:
    driver: local
  opensearch:
    driver: local
  pg-IVFFlat:
    driver: local
  pg-HNSW:
    driver: local
  qdrant:
    driver: local
