services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - ELASTIC_PASSWORD=changeme
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  pgvector-IVFFlat:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: pgvector-ivfflat
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata-IVFFlat:/var/lib/postgresql/data
  pgvector-HNSW:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: pgvector-hnsw
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata-HNSW:/var/lib/postgresql/data

volumes:
  esdata:
    driver: local
  pgdata-IVFFlat:
    driver: local
  pgdata-HNSW:
    driver: local
