services:
  fastapi-pillow:
    build: ./fastapi-pillow
    ports:
      - "8081:8080"
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 4G