services:
  fastapi-pillow:
    build: ./fastapi-pillow
    ports:
      - "8081:8080"
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 8G
  golang-std:
    build: ./golang-std
    ports:
      - "8082:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 8G
  fastify-sharp:
    build: ./fastify-sharp
    ports:
      - "8083:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - HOST=0.0.0.0
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 8G
  hyper-imagers:
    build: ./hyper_imagers
    ports:
      - "8084:8080"
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 8G