[project]
name = "image-processing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "locust>=2.37.14",
]

[tool.uv.workspace]
members = [
    "fastapi-pillow",
]
