services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: q1w2e3r4
      POSTGRES_DB: benchmark
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: -c 'max_connections=1000'
    ports:
      - "15432:5432"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8096M

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: kafka
    user: "0:0"  # root 권한으로 실행
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      # KRaft 모드 설정 (Zookeeper 없이 실행)
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      
      # 클러스터 ID (임의의 base64 UUID)
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      
      # 성능 및 설정
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 8
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_MS: 86400000
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
      
      # KRaft 관련 설정
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    volumes:
      - kafka-logs:/var/lib/kafka/data
    command: >
      bash -c "
        # 디렉토리 권한 설정
        mkdir -p /var/lib/kafka/data &&
        chmod 755 /var/lib/kafka/data &&
        chown -R appuser:appuser /var/lib/kafka/data &&
        
        # KRaft 모드로 Kafka 시작
        /etc/confluent/docker/run
      "
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8096M

volumes:
  pgdata:
    driver: local
  kafka-logs:
    driver: local
