[package]
name = "database_write_performance"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
rand = "0.9.2"
tokio = { version = "1.47.1", features = ["full"] }
uuid = { version = "1.18.0", features = ["v4"] }

[[bin]]
name = "main"
path = "./src/main.rs"

[[bin]]
name = "gen"
path = "./src/generate.rs"
