services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: q1w2e3r4
      POSTGRES_DB: benchmark
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8096M
  mysql: 
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: q1w2e3r4
      MYSQL_DATABASE: benchmark
      MYSQL_USER: user
      MYSQL_PASSWORD: q1w2e3r4
    ports:
      - "13306:3306"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8096M

volumes:
  pgdata:
    driver: local
